### PR TITLE
Touch auth_file to indicate that authentication is completed

### PR DESCRIPTION
**Pull request by maximbaz**
Hey @a-dma, this is what I had in mind in #77 and it actually seems to work! 

I did see the note in the README about this project being on a security maintenance mode, but since it's a pretty simple change that doesn't seem to impose any security risk, would you consider merging it? 

If no merge a is very strict rule, then close it.

### CODE REVIEW

**Comment by a-dma** [comment]
As we won't be doing a new release of this, I don't think that merging code to this project makes sense.
I hope you don't mind me closing.

As I side note, I wouldn't want anything touching the authfile, I'd rather use a tempfile/pidfile and maybe add a module option for that

**Comment by maximbaz** [comment]
Then consider this as a feature request for the new project that you are working on as a replacement for this one 😉

**Comment by a-dma** [comment]
Will do!

**Comment by maximbaz** [comment]
@a-dma since the project [is not being rewritten for now](https://github.com/Yubico/pam-u2f/pull/84#issuecomment-381623510), may I create a feature request for this?  

So far I have been using my own fork with the change in this PR in order to implement [yubikey-touch-detector](https://github.com/maximbaz/yubikey-touch-detector), but if this gets implemented in a more sophisticated way (e.g. with pidfile as you suggested), I would be happy to adapt the detector code.

**Comment by a-dma** [comment]
Sure thing! I like the idea.

How about having something like `/var/run/user/$UID/pam-u2f-touch` to signify pam-u2f waiting for touch?

**Comment by maximbaz** [comment]
Sounds good to me, created #88 to track this feature request 👍

**Pull request closed without merging**
