### PR TITLE
Add FIDO 2 support

### PR DESCRIPTION
**Pull request by martelletto**
This series of commits switches pam-u2f to libfido2, adding support for the following FIDO 2 features:

- resident keys;
- 2048-bit RSA;
- assertions without the user's presence.

### CODE REVIEW

**Comment by fgervais** [comment]
Will this allow the [Feitian BioPass FIDO2](https://www.ftsafe.com/onlinestores/product?id=3) to work with the lib?

**Comment by fgervais** [comment]
This seems like a pretty official kind of PR.

Any idea why it's not getting merged? Is there concerns?

**Comment by martelletto** [comment]
we are waiting for libfido2's api to mature. i will make a 1.0 
release of libfido2 soon, after which we will reconsider this PR. 
there shouldn't be major changes, as not much changed in libfido2.

if you are interested, you are welcome to give it a try in the 
meantime :)

-p.

**Comment by fgervais** [comment]
I'm just lazily posting this here before I start digging into the spec.

I tried the biopass fido2 adapter and I get this:

```
fgervais@bionic_18041-yubico:~/pam-u2f$ pamu2fcfg -v -d -t es256
Setting origin to pam://bionic_18041-yubico
Setting appid to pam://bionic_18041-yubico
Setting user to fgervais
Setting user id to 8326c45fafb8d573c2444b33b2bd9284482ab739ba4238ba06844baa97dc00f1
get_report_descriptor: open
get_report_descriptor: open
get_report_descriptor: open
get_report_descriptor: open
get_report_descriptor: open
get_report_descriptor: open
tx: d=0x562b9c2361c0, cmd=0x86, buf=0x562b9c2361c0, count=8
  4f 51 da 5c 78 09 44 5d 
rx: initiation frame at 0x7ffdf6bbc370, len 64
  ff ff ff ff 86 00 11 4f 51 da 5c 78 09 44 5d 00 
  00 00 0b 02 01 00 01 0d 00 00 00 00 00 00 00 00 
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
tx: d=0x562b9c2361c0, cmd=0x90, buf=0x562b9c233dc0, count=180
  01 a4 01 58 20 b9 03 4e 0e db af 4a 3b f6 16 9a 
  1e fc 02 db c1 f2 c9 06 6a 6c 58 b7 08 52 ec 64 
  8b df a7 ff 37 02 a2 62 69 64 78 19 70 61 6d 3a 
  2f 2f 62 69 6f 6e 69 63 5f 31 38 30 34 31 2d 79 
  75 62 69 63 6f 64 6e 61 6d 65 78 19 70 61 6d 3a 
  2f 2f 62 69 6f 6e 69 63 5f 31 38 30 34 31 2d 79 
  75 62 69 63 6f 03 a2 62 69 64 58 20 83 26 c4 5f 
  af b8 d5 73 c2 44 4b 33 b2 bd 92 84 48 2a b7 39 
  ba 42 38 ba 06 84 4b aa 97 dc 00 f1 64 6e 61 6d 
  65 68 66 67 65 72 76 61 69 73 04 81 a2 63 61 6c 
  67 39 00 06 64 74 79 70 65 6a 70 75 62 6c 69 63 
  2d 6b 65 79 
rx: initiation frame at 0x7ffdf6bbbac0, len 64
  00 00 00 0b 90 00 01 26 00 00 00 00 00 00 00 00 
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
parse_cbor_reply: blob[0]=0x26
fido_dev_make_cred_rx: parse_makecred_reply
error: fido_dev_make_cred (38) FIDO_ERR_UNSUPPORTED_ALGORITHM
```

In there datasheet they don't specify much but they list the supported "Security Algorithm"s to be "ECDSA, SHA256, AES, HMAC, ECDH". I not sure if any of these could work in this case.

I feel I'm quite hacking that pull request channel with this. Should I post that in an issue somewhere?

**Comment by martelletto** [comment]
Hi,

This is unlikely to be a problem in pam-u2f. It is either a bug in 
libfido2 or a misunderstanding about the flavour of ECDSA supported 
by the key. Could you open an issue in the libfido2 repo?

Thank you,

-p.

**Comment by fgervais** [comment]
Yes I will, thank you for your thoughts.

**Comment by fgervais** [comment]
Using this PR, pam_u2f doesn't seem to request user verification.

Is there a parameter I can use to require uv? I'd like that so fingerprint verification is required with the biopass adapter.

**Comment by martelletto** [comment]
for the biopass, the following one-liner could work, provided that 
pamu2fcfg was used to request user presence. for yubico 
authenticators, pam-u2f would need to cue the user for a pin, and 
such a mechanism is currently not implemented in this PR.

-p.

diff --git util.c util.c
index ced0783..4bb4e66 100644
--- util.c
+++ util.c
@@ -661,7 +661,7 @@ int do_authentication(const cfg_t *cfg, const device_t *devices,
               converse(pamh, PAM_TEXT_INFO, DEFAULT_CUE);
             }
             retval = -1;
-            fido_assert_set_options(assert, true, false);
+            fido_assert_set_options(assert, true, true);
             r = fido_dev_get_assert(authlist[j], assert, NULL);
           } else
             continue;

**Comment by martelletto** [comment]
@fgervais, does this branch work with your biometric key?

**Comment by fgervais** [comment]
@martelletto sorry I didn't get to try it yet but I have it in my pipeline, I'll let you know.

**Comment by fgervais** [comment]
@martelletto got the time to try it.

Both userpresence and userverification work. However, userverification does not cue.

**Comment by martelletto** [comment]
Hi @fgervais, thank you for testing. I've re-pushed the last commit with a fix to cue on user verification. The push was forced to fix a typo in the commit message.

**Comment by fgervais** [comment]
Yes, tested again, it does show the cue and still does userverification fine.

**Pull request merged**
