### PR TITLE
Add i10n support

### PR DESCRIPTION
**Pull request by cthbleachbit**
* Added localization frameworks with gettext
* Added translation of Simplified Chinese and Japanese

### CODE REVIEW

**Comment by cthbleachbit** [comment]
Sorry I noticed some problems in autotool define. Fixing now

**Comment by a-dma** [comment]
Hi.

Thanks for the contribution. I haven't had a close look at your PR yet.
In principle I'm not against merging this. However, as advertised in the README file, this project is being rewritten and will only receive security fixes for the time being.

**Comment by bjornfor** [comment]
@a-dma: Where is the successor project? (I cannot find it.)

**Comment by a-dma** [comment]
It hasn't been released yet.

**Pull request closed without merging**
